/* ==========================================================================
   Variation D -- "Botanical Cozy"
   Curated book catalogue (a distinct subset of the shared Open Library data).
   Genres: Poetry, Philosophy, Biography, Historical Fiction, Children's Fiction, Travel, Science, Drama
   52 titles. Plain global (no modules -- must run from file://).
   ========================================================================== */

const BOOKS = [
  {
    id: "ol-OL20262024W",
    title: "'Twas the Night before Christmas",
    subtitle: "",
    author: "Clement Clarke Moore",
    year: 1912,
    genre: "Poetry",
    rating: null,
    pages: 32,
    publisher: "Highlights for Children",
    language: "English",
    isbn: "1449421873",
    cover: "assets/covers/ol-OL20262024W.jpg",
    coverFrom: "#2e6010",
    coverTo: "#193409",
    tags: ["children's poetry", "santa claus", "christmas", "juvenile poetry"],
    blurb: ["The Coca-Cola Company's Santa are used to illustrate the well-known poem about an important Christmas visitor."],
    quote: { text: "T WAS the night before Christmas, when all through the house", source: "First sentence" }
  },
  {
    id: "ol-OL24165W",
    title: "A Child's Garden of Verses",
    subtitle: "",
    author: "Robert Louis Stevenson",
    year: 1885,
    genre: "Poetry",
    rating: 3.8,
    pages: 116,
    publisher: "Thomas Y. Crowell company",
    language: "English",
    isbn: "0517123975",
    cover: "assets/covers/ol-OL24165W.jpg",
    coverFrom: "#6a0669",
    coverTo: "#3a0339",
    tags: ["children's poetry", "scottish poetry", "poetry", "english poetry"],
    blurb: ["Rediscover the delight and innocence of childhood in these classic poems from celebrated author, Robert Louis Stevenson. From make-believe to climbing trees, bedtime stories to morning play and favourite cousins to beloved mothers. Here is a very special collection to be treasured forever."],
    quote: { text: "When I was down beside the sea, a wooden spade they gave to me to dig the sandy shore.", source: "First sentence" }
  },
  {
    id: "ol-OL15843795W",
    title: "A Light in the Attic",
    subtitle: "",
    author: "Shel Silverstein",
    year: 1981,
    genre: "Poetry",
    rating: 4.3,
    pages: 167,
    publisher: "Harpercollins Childrens Books",
    language: "Spanish",
    isbn: "9780060513061",
    cover: "assets/covers/ol-OL15843795W.jpg",
    coverFrom: "#0d2063",
    coverTo: "#071136",
    tags: ["humorous poetry", "juvenile literature", "children's poetry", "american poetry"],
    blurb: ["A collection of humorous poems and drawings."],
    quote: null
  },
  {
    id: "ol-OL13534159W",
    title: "A Poetry Handbook",
    subtitle: "",
    author: "Mary Oliver",
    year: 1994,
    genre: "Poetry",
    rating: 4.3,
    pages: 137,
    publisher: "Harcourt Brace & Company",
    language: "English",
    isbn: "9780156724005",
    cover: "assets/covers/ol-OL13534159W.jpg",
    coverFrom: "#165a43",
    coverTo: "#0c3125",
    tags: ["handbooks", "history and criticism", "english poetry", "american poetry"],
    blurb: ["A Poetry Handbook is a poetry work by Mary Oliver, first published in 1994. The edition catalogued here runs to 137 pages. It was published by Harcourt Brace & Company.", "Open Library catalogues it under handbooks, history and criticism and english poetry. Readers there give it an average rating of 4.3 out of 5. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL47087W",
    title: "Aeneis",
    subtitle: "",
    author: "Publius Vergilius Maro",
    year: 1592,
    genre: "Poetry",
    rating: 3.4,
    pages: 360,
    publisher: "Echo Library",
    language: "English",
    isbn: "1976546303",
    cover: "assets/covers/ol-OL47087W.jpg",
    coverFrom: "#4a5917",
    coverTo: "#28300d",
    tags: ["classical literature", "history and criticism", "latin epic poetry", "rome in literature"],
    blurb: ["\"Virgil's masterpiece  of Latin poetry, a lively, dramatic poem of daring and adventure, of love and loss, of devotion and death. \""],
    quote: { text: "Of arms I sing and the hero, destiny's exile,", source: "First sentence" }
  },
  {
    id: "ol-OL1865549W",
    title: "Ariel",
    subtitle: "",
    author: "Sylvia Plath",
    year: 1965,
    genre: "Poetry",
    rating: 4.1,
    pages: 96,
    publisher: "HarperCollins",
    language: "English",
    isbn: "0060133589",
    cover: "assets/covers/ol-OL1865549W.jpg",
    coverFrom: "#06496a",
    coverTo: "#03283a",
    tags: ["american poetry", "poetry", "textual criticism", "open_syllabus_project"],
    blurb: ["\"A restored edition of Sylvia Plath's collection of poems that were published after her death that restores the selection and arrangement of the poems as Plath left them at the point of her death.\"", "Upon the publication of her posthumous volume of poetry, Ariel, in the mid-1960s, Sylvia Plath became a household name. Readers may be surprised to learn that the draft of Ariel left behind by Sylvia Plath when she died in 1963 is different from the volume of poetry eventually published to worldwide acclaim. This facsimile edition restores, for the first time, the selection and arrangement of the poems as Sylvia Plath left them at the point of her death."],
    quote: null
  },
  {
    id: "ol-OL97725W",
    title: "Ars Amatoria",
    subtitle: "",
    author: "Ovid",
    year: 1494,
    genre: "Poetry",
    rating: 4.1,
    pages: 201,
    publisher: "Academiae Litterarum Hungaricae",
    language: "English",
    isbn: "0192836331",
    cover: "assets/covers/ol-OL97725W.jpg",
    coverFrom: "#25610f",
    coverTo: "#143508",
    tags: ["love poetry", "love-letters", "poetry", "latin erotic poetry"],
    blurb: ["Originally published Manchester: Carcanet, 2003."],
    quote: { text: "'Arms and Atrocities' -I was preparing my opening salvo in stern Heroic Verse, to match the matter.", source: "First sentence" }
  },
  {
    id: "ol-OL17837119W",
    title: "12 Rules for Life",
    subtitle: "",
    author: "Jordan B. Peterson",
    year: 2015,
    genre: "Philosophy",
    rating: 3.8,
    pages: 480,
    publisher: "Planeta",
    language: "English",
    isbn: "9780345816023",
    cover: "assets/covers/ol-OL17837119W.jpg",
    coverFrom: "#255a16",
    coverTo: "#14310c",
    tags: ["conduct of life", "philosophy", "philosophy / social", "psychology"],
    blurb: ["Duplicate of"],
    quote: null
  },
  {
    id: "ol-OL1088357W",
    title: "A History of Western Philosophy",
    subtitle: "",
    author: "Bertrand Russell",
    year: 1945,
    genre: "Philosophy",
    rating: 4.2,
    pages: 895,
    publisher: "Routledge",
    language: "English",
    isbn: "9780041000450",
    cover: "assets/covers/ol-OL1088357W.jpg",
    coverFrom: "#145b5c",
    coverTo: "#0b3232",
    tags: ["western influences", "philosophy", "political science", "history"],
    blurb: ["[The author's] purpose is to exhibit philosophy as an integral part of social and political life: not as the isolated speculations of remarkable individuals, but as both an effect and a cause of the character of the various communities in which different systems flourished.-Pref."],
    quote: { text: "IN all history, nothing is so surprising or so difficult to account for as the sudden rise of civilization in Greece.", source: "First sentence" }
  },
  {
    id: "ol-OL98130W",
    title: "Also sprach Zarathustra",
    subtitle: "Ein Buch für Alle und Keinen",
    author: "Friedrich Nietzsche",
    year: 1883,
    genre: "Philosophy",
    rating: 4.1,
    pages: 354,
    publisher: "Insel Verlag GmbH",
    language: "English",
    isbn: "1544783892",
    cover: "assets/covers/ol-OL98130W.jpg",
    coverFrom: "#14205c",
    coverTo: "#0b1232",
    tags: ["classic literature", "fiction", "filosofie", "filosofía"],
    blurb: ["A landmark work of philosophy and of literature, Thus Spoke Zarathustra is the fullest expression of Nietzche's belief that \"the object of mankind should lie in its highest individuals.\" In his thirtieth year Zarathustra - the archetypal Ubermensch representative of supreme passion and creativity - abandons his home for the mountains, where he lives, literally and figuratively, on a level of experience far above the conventional standards of good and evil. The exuberant, poetic testimony of Nietzche's great messianic hero (and alter ego) is a vivid demonstration of the philosopher's genius."],
    quote: { text: "When Zarathustra was thirty years old, he left his home and the lake of his home, and went into the mountains.", source: "First sentence" }
  },
  {
    id: "ol-OL21686956W",
    title: "Be Water, My Friend",
    subtitle: "",
    author: "Shannon Lee",
    year: 2020,
    genre: "Philosophy",
    rating: null,
    pages: 240,
    publisher: "Dojo Ediciones",
    language: "English",
    isbn: "1250794838",
    cover: "assets/covers/ol-OL21686956W.jpg",
    coverFrom: "#572b19",
    coverTo: "#30170e",
    tags: ["philosophy", "recreation"],
    blurb: ["Be Water, My Friend is a philosophy work by Shannon Lee, first published in 2020. The edition catalogued here runs to 240 pages. It was published by Dojo Ediciones.", "Open Library catalogues it under philosophy and recreation. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL5814581W",
    title: "Bluets",
    subtitle: "",
    author: "Maggie Nelson",
    year: 2009,
    genre: "Philosophy",
    rating: 4,
    pages: 112,
    publisher: "Wave Books",
    language: "English",
    isbn: "1911214527",
    cover: "assets/covers/ol-OL5814581W.jpg",
    coverFrom: "#611038",
    coverTo: "#35091f",
    tags: ["blue", "color (philosophy)", "philosophy"],
    blurb: ["Bluets is a philosophy work by Maggie Nelson, first published in 2009. The edition catalogued here runs to 112 pages. It was published by Wave Books.", "Open Library catalogues it under blue, color (philosophy) and philosophy. Readers there give it an average rating of 4.0 out of 5. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL15236125W",
    title: "Chto takoe iskusstvo? / What is art?",
    subtitle: "",
    author: "Лев Толстой",
    year: 1898,
    genre: "Philosophy",
    rating: null,
    pages: 237,
    publisher: "H. Altemus",
    language: "English",
    isbn: "9780735102934",
    cover: "assets/covers/ol-OL15236125W.jpg",
    coverFrom: "#1a6709",
    coverTo: "#0e3805",
    tags: ["art", "art and morals", "arts", "arts and morals"],
    blurb: ["Marathi translation of the what is art?, English translation by Charles Johnston from Russian."],
    quote: null
  },
  {
    id: "ol-OL1183657W",
    title: "Die Welt als Wille und Vorstellung",
    subtitle: "",
    author: "Arthur Schopenhauer",
    year: 1819,
    genre: "Philosophy",
    rating: null,
    pages: 514,
    publisher: "Paul, Trench, Trübner",
    language: "German",
    isbn: "8477203903",
    cover: "assets/covers/ol-OL1183657W.jpg",
    coverFrom: "#680852",
    coverTo: "#39042d",
    tags: ["philosophy", "will", "idea (philosophy)", "theory of knowledge"],
    blurb: ["The German philosopher explains his thoughts about intellectual perception and abstract representation and critically analyzes Kant's ideas and teachings. Bibliogs."],
    quote: { text: "O mundo é a minha representação.", source: "First sentence" }
  },
  {
    id: "ol-OL514629W",
    title: "\"Surely You're Joking, Mr. Feynman\"",
    subtitle: "Adventures of a Curious Character",
    author: "Richard Phillips Feynman",
    year: 1984,
    genre: "Biography",
    rating: 4.2,
    pages: 352,
    publisher: "Vintage",
    language: "English",
    isbn: "0393316041",
    cover: "assets/covers/ol-OL514629W.jpg",
    coverFrom: "#640c55",
    coverTo: "#36072e",
    tags: ["anecdotes", "art", "biography", "humor"],
    blurb: ["The biography of the physicist and Nobel prize winner Richard P. Feynman - a collection of short stories, chapters told to and written down by Ralph Leighton.", "Feynman tells of his childhood and youth and goes into his adult life, both personally and professionally."],
    quote: { text: "WHEN I WAS about eleven or twelve I set up a lab in my house.", source: "First sentence" }
  },
  {
    id: "ol-OL937456W",
    title: "A Beautiful Mind",
    subtitle: "",
    author: "Sylvia Nasar",
    year: 1998,
    genre: "Biography",
    rating: 3.2,
    pages: 537,
    publisher: "Columna CAT",
    language: "English",
    isbn: "8466403639",
    cover: "assets/covers/ol-OL937456W.jpg",
    coverFrom: "#145c59",
    coverTo: "#0b3230",
    tags: ["schizophrenics", "schizofrenie", "mathématiciens", "mentally ill"],
    blurb: ["Relates how mathematical genius John Forbes Nash, Jr., suffered a breakdown at age thirty-one and was diagnosed with schizophrenia, but experienced a remission of his illness thirty years later."],
    quote: { text: "AMONG JOHN NASH'S EARLIEST MEMORIES is one in which, as a child of about two or three, he is listening to his maternal grandmother play the piano in the front parlor of the old Tazewell Street house, high on a breezy hill overlooking the city of Bluefield, West Virginia.", source: "First sentence" }
  },
  {
    id: "ol-OL66946W",
    title: "A child called \"it\"",
    subtitle: "",
    author: "David J. Pelzer",
    year: 1987,
    genre: "Biography",
    rating: 4.6,
    pages: 168,
    publisher: "BCA",
    language: "English",
    isbn: "0752832220",
    cover: "assets/covers/ol-OL66946W.jpg",
    coverFrom: "#676509",
    coverTo: "#383705",
    tags: ["biography", "abused children", "foster home care", "abusive mothers"],
    blurb: ["This book chronicles the unforgettable account of one of the most severe child abuse cases in California history. It is the story of Dave Pelzer, who was brutally beaten and starved by his emotionally unstable, alcoholic mother: a mother who played tortuous, unpredictable games--games that left him nearly dead. He had to learn how to play his mother's games in order to survive because she no longer considered him a son, but a slave; and no longer a boy, but an \"it.\"", "Dave's bed was an old army cot in the basement, and his clothes were torn and raunchy. When his mother allowed him the luxury of food, it was nothing more than spoiled scraps that even the dogs refused to eat. The outside world knew nothing of his living nightmare. He had nothing or no one to turn to, but his dreams kept him alive--dreams of someone taking care of him, loving him and calling him their son."],
    quote: { text: "March 5, 1973, Daly City, California-I'm late.", source: "First sentence" }
  },
  {
    id: "ol-OL42308W",
    title: "All Creatures Great and Small (All Creatures Great and Small #1-2)",
    subtitle: "",
    author: "James Herriot",
    year: 1972,
    genre: "Biography",
    rating: 4.3,
    pages: 445,
    publisher: "Bantam Books",
    language: "Spanish",
    isbn: "9780553138597",
    cover: "assets/covers/ol-OL42308W.jpg",
    coverFrom: "#111660",
    coverTo: "#090c34",
    tags: ["veterinarians", "biography", "herriot", "large type books"],
    blurb: ["Delve into the magical, unforgettable world of James Herriot, the world's most beloved veterinarian, and his menagerie of heartwarming, funny, and tragic animal patients.", "For over forty years, generations of readers have thrilled to Herriot's marvelous tales, deep love of life, and extraordinary storytelling abilities. For decades, Herriot roamed the remote, beautiful Yorkshire Dales, treating every patient that came his way from smallest to largest, and observing animals and humans alike with his keen, loving eye."],
    quote: { text: "They didn't say anything about this in the books, I thought, as the snow blew in through the gaping doorway and settled on my naked back.", source: "First sentence" }
  },
  {
    id: "ol-OL1068072W",
    title: "Autobiography",
    subtitle: "",
    author: "John Stuart Mill",
    year: 1873,
    genre: "Biography",
    rating: null,
    pages: 240,
    publisher: "Rocco Carabba",
    language: "German",
    isbn: "9781435337466",
    cover: "assets/covers/ol-OL1068072W.jpg",
    coverFrom: "#135d30",
    coverTo: "#0b331a",
    tags: ["biographies", "philosophy", "philosophers", "filosofen"],
    blurb: ["John Stuart Mill was an English philosopher, political economist, Member of Parliament and civil servant. One of the most influential thinkers in the history of classical liberalism, he contributed widely to social theory, political theory, and political economy"],
    quote: { text: "IT seems proper that I should prefix to the following biographical sketch, some mention of the reasons which have made me think it desirable that I should leave behind me such a memorial of so uneventful a life as mine.", source: "First sentence" }
  },
  {
    id: "ol-OL528094W",
    title: "Autobiography of a Yogi",
    subtitle: "",
    author: "Yogananda Paramahansa",
    year: 1946,
    genre: "Biography",
    rating: 4.2,
    pages: 514,
    publisher: "Empire Books",
    language: "Japanese",
    isbn: "0554224666",
    cover: "assets/covers/ol-OL528094W.jpg",
    coverFrom: "#475a16",
    coverTo: "#27310c",
    tags: ["autobiography", "yogis", "yoga", "yoguis"],
    blurb: ["The autobiography of Paramahansa Yogananda (1893 - 1952) details his search for a guru, during which he encountered many spiritual leaders and world-renowned scientists."],
    quote: { text: "THE CHARACTERISTIC FEATURES of Indian culture have long been a search for ultimate verities and the concomitant disciple-guru relationship.", source: "First sentence" }
  },
  {
    id: "ol-OL3961899W",
    title: "Ball Four",
    subtitle: "",
    author: "Jim Bouton",
    year: 1970,
    genre: "Biography",
    rating: 4,
    pages: 472,
    publisher: "World",
    language: "English",
    isbn: "1469280329",
    cover: "assets/covers/ol-OL3961899W.jpg",
    coverFrom: "#14365d",
    coverTo: "#0b1d33",
    tags: ["baseball", "baseball players", "biography", "joueurs de base-ball"],
    blurb: ["Twentieth-anniversary edition of a baseball classic, with a new epilogue by Jim Bouton. When first published in 1970, Ball Four stunned the sports world. The commissioner, executives, and players were shocked. Sportswriters called author Jim Bouton a traitor and \"social leper.\" Baseball commissioner Bowie Kuhn tried to force him to declare the book untrue. Fans, however, loved the book. And serious critics called it an important social document. Today, Jim Bouton is still not invited to Oldtimer's Days at Yankee Stadium."],
    quote: null
  },
  {
    id: "ol-OL1794622W",
    title: "A Final Reckoning",
    subtitle: "A Tale of Bush Life in Australia",
    author: "G. A. Henty",
    year: 1800,
    genre: "Historical Fiction",
    rating: 4,
    pages: 264,
    publisher: "Creative Media Partners, LLC",
    language: "English",
    isbn: "9781483928197",
    cover: "assets/covers/ol-OL1794622W.jpg",
    coverFrom: "#325e12",
    coverTo: "#1b330a",
    tags: ["fiction", "australia", "juvenile fiction", "large type books"],
    blurb: ["A young English lad, after rather a stormy boyhood, emigrates to Australia and gets employment as an officer in the mounted police. A few years of active work on the frontier, where he has many a brush with both natives and bush-rangers, gain him promotion to a captaincy, and he eventually settles down to the peaceful life of a squatter."],
    quote: null
  },
  {
    id: "ol-OL17113467W",
    title: "A Long Walk to Water( Linda Sue Park)",
    subtitle: "",
    author: "Linda Sue Park",
    year: 2008,
    genre: "Historical Fiction",
    rating: 4.5,
    pages: 136,
    publisher: "Brilliance Audio",
    language: "English",
    isbn: "1936223120",
    cover: "assets/covers/ol-OL17113467W.jpg",
    coverFrom: "#581952",
    coverTo: "#300d2d",
    tags: ["children's fiction", "refugees", "survival", "blacks"],
    blurb: ["When the Sudanese civil war reaches his village in 1985, eleven-year-old Salva becomes separated from his family and must walk with other Dinka tribe members through southern Sudan, Ethiopia, and Kenya in search of safe haven. Based on the life of Salva Dut, who, after emigrating to America in 1996, began a project to dig water wells in Sudan."],
    quote: null
  },
  {
    id: "ol-OL13015026W",
    title: "An echo in the darkness",
    subtitle: "",
    author: "Francine Rivers",
    year: 1994,
    genre: "Historical Fiction",
    rating: 4.5,
    pages: 452,
    publisher: "Thorndike Press",
    language: "Spanish",
    isbn: "9781886463172",
    cover: "assets/covers/ol-OL13015026W.jpg",
    coverFrom: "#624a0f",
    coverTo: "#352808",
    tags: ["fiction", "church history", "women slaves", "historical fiction"],
    blurb: ["This classic series has inspired over half a million readers. Turning away from the opulence of Rome, Marcus is led by a whispering voice from the past into a journey that could set him free from the darkness of his soul.", "A prosperous trader, Marcus Lucianus Valerian has made a fortune providing sand and slaves for the Roman games. But Hadassah, a slave in his family's household, has enchanted him with her quiet beauty and her staunch faith in Christ. When Marcus' sister sends Hadassah to almost certain death in the games, Marcus feels that his life has been ripped apart. Now he is on his way to Jerusalem to find out more about Hadassah's god, unaware that a miracle awaits him back in Rome."],
    quote: { text: "Marcus Lucianus Valerian walked through a maze of streets in the Eternal City, hoping to find a sanctuary of peace within himself.", source: "First sentence" }
  },
  {
    id: "ol-OL15181842W",
    title: "As Sure as the Dawn",
    subtitle: "",
    author: "Francine Rivers",
    year: 1995,
    genre: "Historical Fiction",
    rating: null,
    pages: 500,
    publisher: "Tyndale",
    language: "English",
    isbn: "9781414340913",
    cover: "assets/covers/ol-OL15181842W.jpg",
    coverFrom: "#083869",
    coverTo: "#041f39",
    tags: ["historical fiction", "fiction", "church history", "germanic peoples"],
    blurb: ["Atretes. German warrior. Revered gladiator. He won his freedom through his fierceness . . . but his life is about to change forever.", "Following A Voice in the Wind and An Echo in the Darkness, As Sure as the Dawn continues the chronicles of Hadassah, a Christian slave woman living during the height of the Roman Empire. She has saved the life of the scorned child of a disreputable Roman woman and the Germanic gladiator, Atretes. For her faith, Hadassah now languishes in condemnation, awaiting death in a dungeon beneath the arena. Atretes, who holds fast to his dreams of revenge for the slaughter of his people, wants his son back."],
    quote: { text: "Physically exhausted, pride bruised, Atretes had had enough.", source: "First sentence" }
  },
  {
    id: "ol-OL4476606W",
    title: "Balkan trilogy",
    subtitle: "",
    author: "Olivia Manning",
    year: 1981,
    genre: "Historical Fiction",
    rating: null,
    pages: 924,
    publisher: "William Heinemann Ltd",
    language: "English",
    isbn: "0749304168",
    cover: "assets/covers/ol-OL4476606W.jpg",
    coverFrom: "#0d6323",
    coverTo: "#073613",
    tags: ["english war stories", "fiction", "world war"],
    blurb: ["Balkan trilogy is a historical fiction work by Olivia Manning, first published in 1981. The edition catalogued here runs to 924 pages. It was published by William Heinemann Ltd.", "Open Library catalogues it under english war stories, fiction and world war. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL17690453W",
    title: "Brotherhood of war : the Lieutenants, the Captains, the Majors",
    subtitle: "",
    author: "William E. Butterworth III",
    year: 1991,
    genre: "Historical Fiction",
    rating: null,
    pages: 822,
    publisher: "Dorsett Press",
    language: "English",
    isbn: "0880297123",
    cover: "assets/covers/ol-OL17690453W.jpg",
    coverFrom: "#581852",
    coverTo: "#300d2d",
    tags: ["world war", "fiction", "american war stories"],
    blurb: ["Brotherhood of war : the Lieutenants, the Captains, the Majors is a historical fiction work by William E. Butterworth III, first published in 1991. The edition catalogued here runs to 822 pages. It was published by Dorsett Press.", "Open Library catalogues it under world war, fiction and american war stories. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL97984W",
    title: "Burr",
    subtitle: "a novel",
    author: "Gore Vidal",
    year: 1973,
    genre: "Historical Fiction",
    rating: null,
    pages: 527,
    publisher: "Heinemann",
    language: "Russian",
    isbn: "9781417633845",
    cover: "assets/covers/ol-OL97984W.jpg",
    coverFrom: "#5c5215",
    coverTo: "#322d0b",
    tags: ["historical fiction", "party politics", "scandal", "fiction"],
    blurb: ["At the end of his life Aaron Burr dictates his biography from the Revolutionary War to his treason trial."],
    quote: { text: "Shortly before midnight, July 1, 1833, Colonel Aaron Burr, aged seventy-seven, married Eliza Jurnel, born Bowen fifty-eight years ago (more likely sixty-five but remember: she is prone to litigation!).", source: "First sentence" }
  },
  {
    id: "ol-OL373413W",
    title: "Amba yahaluwo",
    subtitle: "",
    author: "T. B. Ilangaratne",
    year: 1998,
    genre: "Children's Fiction",
    rating: 4,
    pages: 187,
    publisher: "Sarasavi Publishers",
    language: "English",
    isbn: "9789555730587",
    cover: "assets/covers/ol-OL373413W.jpg",
    coverFrom: "#115f16",
    coverTo: "#09340c",
    tags: ["children's stories", "childrens stories", "children's fiction"],
    blurb: ["Novel, for children."],
    quote: null
  },
  {
    id: "ol-OL1898303W",
    title: "And to think that I saw it on Mulberry Street",
    subtitle: "",
    author: "Dr. Seuss",
    year: 1937,
    genre: "Children's Fiction",
    rating: 4.2,
    pages: 32,
    publisher: "Vanguard Press",
    language: "English",
    isbn: "9780679887942",
    cover: "assets/covers/ol-OL1898303W.jpg",
    coverFrom: "#683308",
    coverTo: "#391c04",
    tags: ["children's stories", "fiction", "imagination", "juvenile fiction"],
    blurb: ["\"Dr. Seuss’s very first book for children! From a mere horse and wagon, young Marco concocts a colorful cast of characters, making Mulberry Street the most interesting location in town. Dr. Seuss’s signature rhythmic text, combined with his unmistakable illustrations, will appeal to fans of all ages, who will cheer when our hero proves that a little imagination can go a very long way. (Who wouldn’t cheer when an elephant-pulled sleigh raced by?) Now over seventy-five years old, this story is as timeless as ever."],
    quote: { text: "\"Nothing,\" I said, growing red as a beet, \"But a plain horse and wagon on Mulberry Street.\"", source: "First sentence" }
  },
  {
    id: "ol-OL517198W",
    title: "Are You My Mother?",
    subtitle: "",
    author: "P. D. Eastman",
    year: 1960,
    genre: "Children's Fiction",
    rating: 4.3,
    pages: 63,
    publisher: "Collins & Harvill",
    language: "English",
    isbn: "9780553539899",
    cover: "assets/covers/ol-OL517198W.jpg",
    coverFrom: "#3c620e",
    coverTo: "#213608",
    tags: ["french language", "readers", "animals", "bilingual"],
    blurb: ["A baby bird, fallen from his nest, sets out to find his mother. Spanish and English. Full-color illustrations."],
    quote: { text: "A mother bird sat on her egg.", source: "First sentence" }
  },
  {
    id: "ol-OL15732836W",
    title: "Babička",
    subtitle: "obrazy venkovského života",
    author: "Božena Němcová",
    year: 1855,
    genre: "Children's Fiction",
    rating: null,
    pages: 254,
    publisher: "Čs. spis, t. Stráž, Vimperk",
    language: "English",
    isbn: "8020201076",
    cover: "assets/covers/ol-OL15732836W.jpg",
    coverFrom: "#5e134d",
    coverTo: "#330a2a",
    tags: ["children's stories", "childrens stories", "children's fiction"],
    blurb: ["Babička is a children's fiction work by Božena Němcová, first published in 1855. The edition catalogued here runs to 254 pages. It was published by Čs. spis, t. Stráž, Vimperk.", "Open Library catalogues it under children's stories, childrens stories and children's fiction. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL16224122W",
    title: "Cabin Fever",
    subtitle: "",
    author: "Jeff Kinney",
    year: 2007,
    genre: "Children's Fiction",
    rating: 4.5,
    pages: 218,
    publisher: "Amulet Books",
    language: "Japanese",
    isbn: "180416030X",
    cover: "assets/covers/ol-OL16224122W.jpg",
    coverFrom: "#644b0c",
    coverTo: "#362907",
    tags: ["families", "middle schools", "diary fiction", "juvenile fiction"],
    blurb: ["Greg Heffley is in big trouble. School property has been damaged, and Greg is the prime suspect. But the crazy thing is, he’s innocent. Or at least sort of.", "The authorities are closing in, but when a surprise blizzard hits, the Heffley family is trapped indoors. Greg knows that when the snow melts he’s going to have to face the music, but could any punishment be worse than being stuck inside with your family for the holidays?"],
    quote: null
  },
  {
    id: "ol-OL5759973W",
    title: "Cat the cat, who is that?",
    subtitle: "",
    author: "Mo Willems",
    year: 2010,
    genre: "Children's Fiction",
    rating: 3.9,
    pages: 22,
    publisher: "Balzer & Bray",
    language: "English",
    isbn: "0061728411",
    cover: "assets/covers/ol-OL5759973W.jpg",
    coverFrom: "#693b07",
    coverTo: "#392004",
    tags: ["friendship", "cats", "animals", "fiction"],
    blurb: ["An exuberant cat introduces readers to her friends."],
    quote: null
  },
  {
    id: "ol-OL4126065W",
    title: "Checkmate CD (Abridged)",
    subtitle: "",
    author: "Malorie Blackman",
    year: 2005,
    genre: "Children's Fiction",
    rating: 4.1,
    pages: 481,
    publisher: "Doubleday",
    language: "English",
    isbn: "0552551945",
    cover: "assets/covers/ol-OL4126065W.jpg",
    coverFrom: "#2f5818",
    coverTo: "#19300d",
    tags: ["fiction", "juvenile fiction", "terrorismus", "terrorism"],
    blurb: ["A dramatic and moving conclusion to the award-winning Noughts & Crosses trilogyCan the future ever erase the past? Rose has a Cross mother and a nought father in a society where the pale-skinned noughts are treated as inferiors and those with dual heritage face a life-long battle against deep-rooted prejudices. Sephy, her mother, has told Rose virtually nothing about her father, but as Rose grows into a young adult, she unexpectedly discovers the truth about her parentage and becomes determined to find out more, to honour both sides of her heritage."],
    quote: null
  },
  {
    id: "ol-OL276475W",
    title: "A little tour in France",
    subtitle: "",
    author: "Henry James",
    year: 1884,
    genre: "Travel",
    rating: null,
    pages: 255,
    publisher: "Kessinger Publishing",
    language: "English",
    isbn: "1419102141",
    cover: "assets/covers/ol-OL276475W.jpg",
    coverFrom: "#12415e",
    coverTo: "#0a2333",
    tags: ["description and travel", "travel", "journeys", "american novelists"],
    blurb: ["A little tour in France is a travel work by Henry James, first published in 1884. The edition catalogued here runs to 255 pages. It was published by Kessinger Publishing.", "Open Library catalogues it under description and travel, travel and journeys. This record describes the English edition."],
    quote: { text: "I am ashamed to begin with saying that Touraine is the garden of France; that remark has long ago lost its bloom.", source: "First sentence" }
  },
  {
    id: "ol-OL2431377W",
    title: "A Short Walk in the Hindu Kush",
    subtitle: "",
    author: "Eric Newby",
    year: 1958,
    genre: "Travel",
    rating: null,
    pages: 253,
    publisher: "Make Beiluo wen hua shi ye gu fen you xian gong si",
    language: "English",
    isbn: "9789578278035",
    cover: "assets/covers/ol-OL2431377W.jpg",
    coverFrom: "#5f5d11",
    coverTo: "#343309",
    tags: ["travelogue", "travel", "description and travel", "hindu kush mountains"],
    blurb: ["It is an autobiographical travelogue of Eric Newby,describing,in a comic,understated style,his ascent to Mir Samir."],
    quote: null
  },
  {
    id: "ol-OL3583229W",
    title: "A Time of Gifts",
    subtitle: "On Foot to Constantinople - From the Hook of Holland to the Middle Danube",
    author: "Patrick Leigh Fermor",
    year: 1977,
    genre: "Travel",
    rating: 4.4,
    pages: 304,
    publisher: "New York Review Books",
    language: "English",
    isbn: "1529369525",
    cover: "assets/covers/ol-OL3583229W.jpg",
    coverFrom: "#076945",
    coverTo: "#043926",
    tags: ["travel", "description and travel", "walking", "europe"],
    blurb: ["Leigh Fermor walked from London to Budapest when he was 18. Sometimes called England's greatest travel writer."],
    quote: null
  },
  {
    id: "ol-OL74123W",
    title: "A Walk in the Woods",
    subtitle: "",
    author: "Bill Bryson",
    year: 1997,
    genre: "Travel",
    rating: 3.9,
    pages: 328,
    publisher: "Anchor Books",
    language: "English",
    isbn: "9780786215133",
    cover: "assets/covers/ol-OL74123W.jpg",
    coverFrom: "#16285b",
    coverTo: "#0c1631",
    tags: ["description and travel", "natural history", "travel", "journeys"],
    blurb: ["Bill Bryson describes his attempt to walk the Appalachian Trail with his friend \"Stephen Katz\". The book is written in a humorous style, interspersed with more serious discussions of matters relating to the trail's history, and the surrounding sociology, ecology, trees, plants, animals and people."],
    quote: null
  },
  {
    id: "ol-OL55670W",
    title: "A week on the Concord and Merrimack Rivers",
    subtitle: "",
    author: "Henry David Thoreau",
    year: 1849,
    genre: "Travel",
    rating: null,
    pages: 355,
    publisher: "Dover Publications",
    language: "English",
    isbn: "1985361019",
    cover: "assets/covers/ol-OL55670W.jpg",
    coverFrom: "#555c15",
    coverTo: "#2e320b",
    tags: ["description and travel", "journeys", "gift books", "fiction"],
    blurb: ["Thoreau's first book excels at depicting nature around his trip in words."],
    quote: null
  },
  {
    id: "ol-OL279664W",
    title: "AAA Essential Guide",
    subtitle: "",
    author: "AAA",
    year: 2000,
    genre: "Travel",
    rating: null,
    pages: 126,
    publisher: "AAA",
    language: "English",
    isbn: "9780658006340",
    cover: "assets/covers/ol-OL279664W.jpg",
    coverFrom: "#550b66",
    coverTo: "#2e0637",
    tags: ["automobile travel", "formentera", "ibiza (spain)"],
    blurb: ["AAA Essential Guide is a travel work by AAA, first published in 2000. The edition catalogued here runs to 126 pages. It was published by AAA.", "Open Library catalogues it under automobile travel, formentera and ibiza (spain). This record describes the English edition."],
    quote: { text: "Israel is a fascinating fusion of East and West, ancient and modern, sacred and profane.", source: "First sentence" }
  },
  {
    id: "ol-OL24147W",
    title: "Across the plains",
    subtitle: "with other memories and essays",
    author: "Robert Louis Stevenson",
    year: 1892,
    genre: "Travel",
    rating: null,
    pages: 235,
    publisher: "C. Scribner's Sons",
    language: "English",
    isbn: "1596053127",
    cover: "assets/covers/ol-OL24147W.jpg",
    coverFrom: "#455c14",
    coverTo: "#26320b",
    tags: ["description and travel", "calif monterey", "description", "west (u.s.)"],
    blurb: ["Leaves from the notebook of an emigrant between New York and San Fancisco"],
    quote: null
  },
  {
    id: "ol-OL1892618W",
    title: "A Briefer History of Time",
    subtitle: "",
    author: "Stephen Hawking",
    year: 2005,
    genre: "Science",
    rating: 3.7,
    pages: 176,
    publisher: "Bantam Dell Pub Group",
    language: "Russian",
    isbn: "8377852969",
    cover: "assets/covers/ol-OL1892618W.jpg",
    coverFrom: "#5f0b65",
    coverTo: "#340637",
    tags: ["cosmology", "science / cosmology", "science", "nonfiction"],
    blurb: ["The science classic made more accessible and more concise. Illustrated. Updated with new research.Stephen Hawking's worldwide bestseller, A Brief History of Time, has been a landmark volume in scientific writing. Its author's engaging voice is one reason, and the compelling subjects he addresses is another: the nature of space and time, the role of God in creation, the history and future of the universe."],
    quote: null
  },
  {
    id: "ol-OL8461625W",
    title: "A-level physics",
    subtitle: "",
    author: "Roger Muncaster",
    year: 1981,
    genre: "Science",
    rating: null,
    pages: 953,
    publisher: "Thornes",
    language: "English",
    isbn: "0748717390",
    cover: "assets/covers/ol-OL8461625W.jpg",
    coverFrom: "#0c6462",
    coverTo: "#073636",
    tags: ["physics", "problems", "textbooks"],
    blurb: ["A-level physics is a science work by Roger Muncaster, first published in 1981. The edition catalogued here runs to 953 pages. It was published by Thornes.", "Open Library catalogues it under physics, problems and textbooks. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL16025198W",
    title: "Active physics",
    subtitle: "",
    author: "Arthur Eisenkraft",
    year: 1998,
    genre: "Science",
    rating: 4.3,
    pages: 332,
    publisher: "It's About Time, Inc, Herf Jones Education Division",
    language: "English",
    isbn: "1891629077",
    cover: "assets/covers/ol-OL16025198W.jpg",
    coverFrom: "#64310d",
    coverTo: "#361b07",
    tags: ["textbooks", "science", "physics textbooks", "science textbooks"],
    blurb: ["6 v. : ill.; 27 cm + teacher's edition (6 v. : ill. ; 28 cm)"],
    quote: null
  },
  {
    id: "ol-OL10483518W",
    title: "Advanced Level Physics",
    subtitle: "",
    author: "Michael Nelkon",
    year: 1958,
    genre: "Science",
    rating: 3.8,
    pages: 1079,
    publisher: "Heinemann Educational Books",
    language: "English",
    isbn: "9780435923037",
    cover: "assets/covers/ol-OL10483518W.jpg",
    coverFrom: "#436907",
    coverTo: "#253904",
    tags: ["physics", "textbooks", "problems", "literary collections"],
    blurb: ["Advanced Level Physics is a science work by Michael Nelkon, first published in 1958. The edition catalogued here runs to 1079 pages. It was published by Heinemann Educational Books.", "Open Library catalogues it under physics, textbooks and problems. Readers there give it an average rating of 3.8 out of 5. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL2698159W",
    title: "An introduction to the physics of nuclei and particles",
    subtitle: "",
    author: "R. A. Dunlap",
    year: 2003,
    genre: "Science",
    rating: null,
    pages: 284,
    publisher: "Thomson/Brooks-Cole",
    language: "English",
    isbn: "0534392946",
    cover: "assets/covers/ol-OL2698159W.jpg",
    coverFrom: "#620e4c",
    coverTo: "#350829",
    tags: ["nuclear physics", "physics", "science"],
    blurb: ["An introduction to the physics of nuclei and particles is a science work by R. A. Dunlap, first published in 2003. The edition catalogued here runs to 284 pages. It was published by Thomson/Brooks-Cole.", "Open Library catalogues it under nuclear physics, physics and science. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL1879309W",
    title: "Applied physics",
    subtitle: "",
    author: "Dale Ewen",
    year: 1997,
    genre: "Science",
    rating: null,
    pages: 753,
    publisher: "Prentice Hall",
    language: "English",
    isbn: "9780134159386",
    cover: "assets/covers/ol-OL1879309W.jpg",
    coverFrom: "#515818",
    coverTo: "#2c300d",
    tags: ["textbooks", "physics", "physics.", "applied physics"],
    blurb: ["Applied physics is a science work by Dale Ewen, first published in 1997. The edition catalogued here runs to 753 pages. It was published by Prentice Hall.", "Open Library catalogues it under textbooks, physics and physics.. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL342141W",
    title: "Atomic physics",
    subtitle: "",
    author: "J. B. Rajam",
    year: 1966,
    genre: "Science",
    rating: 4.4,
    pages: 1279,
    publisher: "S. Chand",
    language: "English",
    isbn: "",
    cover: "assets/covers/ol-OL342141W.jpg",
    coverFrom: "#30145d",
    coverTo: "#1a0b33",
    tags: ["nuclear physics", "physics", "science"],
    blurb: ["Atomic physics is a science work by J. B. Rajam, first published in 1966. The edition catalogued here runs to 1279 pages. It was published by S. Chand.", "Open Library catalogues it under nuclear physics, physics and science. Readers there give it an average rating of 4.4 out of 5. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL16249343W",
    title: "A Doll's House",
    subtitle: "",
    author: "Henrik Ibsen",
    year: 1889,
    genre: "Drama",
    rating: 4.3,
    pages: 112,
    publisher: "Joe Books Inc.",
    language: "English",
    isbn: "9798522308643",
    cover: "assets/covers/ol-OL16249343W.jpg",
    coverFrom: "#12525e",
    coverTo: "#0a2d33",
    tags: ["drama", "wives", "norwegian drama", "husband and wife"],
    blurb: ["Translation of Doll's house, English translation of Norwegian original by William Archer."],
    quote: { text: "Hide the Christmas Tree carefully, Helen.", source: "First sentence" }
  },
  {
    id: "ol-OL4644726W",
    title: "A handbook for the study of drama",
    subtitle: "",
    author: "Lynn Altenbernd",
    year: 1966,
    genre: "Drama",
    rating: null,
    pages: 85,
    publisher: "University Press of America",
    language: "English",
    isbn: "0819172642",
    cover: "assets/covers/ol-OL4644726W.jpg",
    coverFrom: "#0b654d",
    coverTo: "#06372a",
    tags: ["drama", "study and teaching"],
    blurb: ["A handbook for the study of drama is a drama work by Lynn Altenbernd, first published in 1966. The edition catalogued here runs to 85 pages. It was published by University Press of America.", "Open Library catalogues it under drama and study and teaching. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL2916090W",
    title: "A Raisin in the Sun",
    subtitle: "",
    author: "Lorraine Hansberry",
    year: 1958,
    genre: "Drama",
    rating: 3.6,
    pages: 151,
    publisher: "Everbind Books",
    language: "English",
    isbn: "0679755314",
    cover: "assets/covers/ol-OL2916090W.jpg",
    coverFrom: "#5b153e",
    coverTo: "#310c22",
    tags: ["drama", "history", "afro-americans", "african americans"],
    blurb: ["This groundbreaking play starred Sidney Poitier, Claudia McNeill, Ruby Dee and Diana Sands in the Broadway production which opened in 1959. Set on Chicago's South Side, the plot revolves around the divergent dreams and conflicts within three generations of the Younger family: son Walter Lee, his wife Ruth, his sister Beneatha, his son Travis and matriarch Lena, called Mama. When her deceased husband's insurance money comes through, Mama dreams of moving to a new home and a better neighborhood in Chicago.", "The tensions and prejudice they face form this seminal American drama. Sacrifice, trust and love among the Younger family and their heroic struggle to retain dignity in a harsh and changing world is a searing and timeless document of hope and inspiration. Winner of the NY Drama Critic's Award as Best Play of the Year, it has been hailed as a \"pivotal play in the history of the American Black theatre.\" by Newsweek and \"a milestone in the American Theatre.\" by Ebony."],
    quote: { text: "The YOUNGER living room would be a comfortable and well-ordered room if it were not for a number of indestructible contradictions to this state of being.", source: "First sentence" }
  }
];
